name: lexicographical_order
description: A string generator that helps to implement real-time editing of an ordered sequence. this makes reordering transactions faster and simpler. 
version: 1.3.4
repository: https://github.com/sylfreee/lexicographical_order
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  equatable: ^2.0.3
  fast_immutable_collections: ^7.3.1
  to_string_pretty: