name: lexicographical_order
description: A string generator that helps to implement a lexicographical order(lexical order). this makes reordering transactions faster and simpler. 
version: 1.3.2
repository: https://github.com/sylfreee/lexicographical_order
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
